### ISSUE TITLE
Do check the extensions are mandatory?

### ISSUE THREAD

**Issue by konacert** [fido-alliance/conformance-tools-issues#459]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 

## What is your implementation class?

Authenticator

## What is the version of the tool are you using?
v1.0.0

## What is the OS and the version are you running?
Windows 7

## Issue description
According to the issue #453 , this issue has been fixed with the tool version 1.0.0.
But when I tested with the tool, the tool mandatory checks extensions return value with authenticatorGetAssertion command. (The fail reason is same as #431 )
Our authenticator does not return any extensions and we do not add any extensions in the metadata.
How can I solve this problem?

**Comment by herrjemand** [comment]
Fixed in 1.0.1. Will release build today

**Comment by konacert** [comment]
> Fixed in 1.0.1. Will release build today
We updated with v1.1.0 but the issues not fixed.
Could you please confirm this issue one more time?

**Comment by herrjemand** [comment]
@konacert there is a typoe. I meant 1.1.0
