### ISSUE TITLE
Root Certificate Verification failing for Andorid Safetynet and Android Keystore 

### ISSUE THREAD

**Issue by kishorechandran41** [fido-alliance/conformance-tools-issues#486]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?
FIDO Conformance Tools v1.1.4(FIDO2 )

## What is the OS and the version are you running?
Windows 10

## Issue description
I am trying to verify that the last certificate present in the certificate chain is a Root certificate or not, possibly from Google in my case, but when I do the root certificate check the same is failing. Is it mandatory/optional to verify the root certificate in case of Andorid Safetynet and Android Keystore. Googled has advised to verify the certificate please confirm.

**Comment by sbweeden** [comment]
You have not provided any details as to why it is failing, but perhaps could be related to #489 and #490

**Comment by herrjemand** [comment]
Fixed now!

**Comment by kishorechandran41** [comment]
@herrjemand v1.1.5 has some issues, posted it as separate issue https://github.com/fido-alliance/conformance-tools-issues/issues/494

**Comment by kishorechandran41** [comment]
The issue still exists more detailed explanation for Andorid Safetynet is in https://github.com/fido-alliance/conformance-tools-issues/issues/500 and for Android Keystore is in https://github.com/fido-alliance/conformance-tools-issues/issues/499
